### ISSUE TITLE
Missing source tarbal on pypi for 2.7.0

### ISSUE THREAD

**Issue by mboisson** [DanielBok/nlopt-python#7]
Hi,
pypi does not have the source tarball for NLopt-python 2.7.0. Is that expected ?

Thanks

**Comment by DanielBok** [comment]
Yup. It's the expected behaviour. We build the source from the original repo. https://github.com/stevengj/nlopt

The goal of the repo is to build wheels for as many platforms as possible. If your platform isn't supported, I think the best way is to build from the source repo. The reason being that it's hard for me to replicate all possible platform combinations. 

😅

**Comment by mboisson** [comment]
We already have NLOPT installed and built. What we want is the python bindings/package, without the NLOPT library itslef. Isn't that what the current repository is about ?

**Comment by DanielBok** [comment]
Nope. I think the repo is meant for people who wants to use nlopt in python but do not know how to build the nlopt source and the python bindings. 

So it attempts to do both. When they pip install the package, it comes with the python bindings along with the nlopt.dll (windows) or nlopt.s (Linux and Mac). 

I would believe that those who knows how to build the code from the original source wouldn't really need what the repo provides. Since if they could build the source with all the cmake and what not, a simple swig to build the python bindings would be a walk in the park.
